#ChatLogin plugin default configuration
---
#show ChatLogin prefix
show-prefix: true
#Register message
register-message: "&0•&bType Your Password &c2 &bTimes In Chat To Register"
#Require password confirmation for registration
password-confirm-required: true
#Register confirmation message
register-confirm-message: "&0•&bPlease Re-Enter Password To Confirm"
#No register permissions message
no-register-permissions: "&cYou don't have permissions to register"
#Login message
login-message: "&0•&bType Your Password In Chat To Login"
#No login permissions message
no-login-permissions: "&cYou don't have permissions to login"
...
